### ISSUE TITLE
Trailer error

### ISSUE THREAD

**Issue by 87fox87** [jeppevinkel/jellyfin-tizen-builds#87]
Hello,
Thank you for your amazing port.

I was sideloading it via @PatrickSt1991's Installer to my the frame 2021 running tizen 6.

I am experiencing an error trying to start a trailer i think. It's the Icon looking like a camera roll.

![Image](https://github.com/user-attachments/assets/0cdc019e-f2dd-4f53-80aa-1fd5aad99d14)

![Image](https://github.com/user-attachments/assets/d61e3a70-3783-4c3a-b822-a25a0c5690a0)

Also wondering how frequent i will have to reinstall. Do updates deleting the app happen a lot to your experience?

**Comment by jeppevinkel** [comment]
I haven't encountered that error before, so I'm not sure how to help with it. It's probably better to seek help on https://github.com/jellyfin/jellyfin-web where the actual client is developed, or https://github.com/jellyfin/jellyfin-tizen where the wrapper that makes it work on Tizen TVs is developed.  

As for updates. In my experience, you shouldn't need to delete the app to update as long as the update is done with the same certificate as the one you initially used when installing the app. I don't update my TV very frequently. Only when there's a server update that makes my current app stop working, or if I have a particular issue that's fixed in a newer version.

**Comment by spoonTRex** [comment]
@quantatheist could you play trailers, though? I'm on 10.11.2. I tried what you did, and it was still an issue.

**Comment by jeppevinkel** [comment]
> [@87fox87](https://github.com/87fox87) [@quantatheist](https://github.com/quantatheist) [@tasken](https://github.com/tasken) I fixed the issue but it does require you to install jellyfin through the app Jellyfin2Samsung with the setting **Fix YouTube error 153** enabled

Do you know if this issue still exists and would it be worth applying the fix directly in the builds here?

**Comment by PatrickSt1991** [comment]
Yeah the issue still exists.

Uhm yeah we can but i think it would be better to create a new build containing that fix? Cause it does require using a tizen service and therefore it won't run on tizen 2.4 anymore

**Comment by jeppevinkel** [comment]
I can just add it as a new option in my matrix of different build types so it's build with a unique name like the others I have.

**Comment by jeppevinkel** [comment]
Also, would you be okay with me using the patch code you've made? I will of course make sure to credit you.

**Comment by PatrickSt1991** [comment]
@jeppevinkel dude, by al means! Your like the Jellyfin demi God with all the builds you've done 😁

**Comment by jeppevinkel** [comment]
> [@jeppevinkel](https://github.com/jeppevinkel) dude, by al means! Your like the Jellyfin demi God with all the builds you've done 😁

You give me too much credit lol. I only barely maintain this currently with coming back once every few months to break whatever has broken.
I'm pretty sure much more time and effort has gone into your project at this point.

**Comment by jeppevinkel** [comment]
I don't have a suitable setup to test this myself, but I've tried porting the fix from Apps2Samsung over now.

Does anyone in this thread have a TV where they can test a build on to see if it works? All the ones with `TrailerFix` in the name here contain the patch: https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2026-07-15-2047.

**Comment by PatrickSt1991** [comment]
I'm on holiday right now but when I'm back I can test it

**Comment by jeppevinkel** [comment]
Thanks. Enjoy your holiday! 😄

**Comment by ilankas** [comment]
Confirming, Trailer fix worked!

_Please excuse me for image quality_
<img width="5712" height="4284" alt="Image" src="https://github.com/user-attachments/assets/de0b1477-7713-4d2e-957c-65b9797c2ddb" />

<img width="5712" height="4284" alt="Image" src="https://github.com/user-attachments/assets/0c54ff55-ec04-4971-a561-0cb35f8871b7" />

TV: Samsung QE65S90FAT
Jellyfin Server version: 10.11.11
Wondering if same fix can be/will be applied also to "SmartHub" widgets, please?

**Comment by PatrickSt1991** [comment]
@jeppevinkel it works

**Comment by williameggers** [comment]
@jeppevinkel are you still planning on merging this feature branch into master?
